DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(ID bigint generated BY default as identity NOT NULL,
                   BOOK_NAME VARCHAR(255) NOT NULL COMMENT '图书名称',
                   COUNT INT NOT NULL COMMENT '图书数量',
                   UNIT_PRICE DECIMAL(10,2) NOT NULL COMMENT '图书单价',
                   CREATE_TIME DATETIME COMMENT'创建时间',
                   MODIFY_TIME DATETIME COMMENT'修改时间',
                   ENABLE_FLAG VARCHAR(2) DEFAULT 'Y' NOT NULL COMMENT'状态'
);

DROP TABLE IF EXISTS MEMBERS;
CREATE TABLE MEMBERS(ID bigint generated BY default as identity NOT NULL,
                   MEMBER_NAME VARCHAR(255) NOT NULL COMMENT '会员名称',
                   MEMBER_NO VARCHAR(20) NOT NULL COMMENT '会员号码',
                   MEMBER_TYPE VARCHAR(20) NOT NULL COMMENT '会员类型',
                   ENABLE_FLAG VARCHAR(2) DEFAULT 'Y' NOT NULL COMMENT'状态',
                   CREATE_TIME DATETIME COMMENT'创建时间',
                   POINTS INT NOT NULL COMMENT '积分总额'
);

DROP TABLE IF EXISTS ORDERS;
CREATE TABLE ORDERS(ID bigint generated BY default as identity NOT NULL,
                     MEMBERS_ID bigint NOT NULL COMMENT '会员ID',
                     CREATE_TIME DATETIME COMMENT'创建时间',
                     ORDER_TIME DATETIME COMMENT'下单时间',
                     TOTAL_PRICE INT NOT NULL COMMENT '订单总金额',
                     ORDER_STATUE VARCHAR(2) NOT NULL COMMENT'订单状态'
);

DROP TABLE IF EXISTS ORDERS_DETAILS;
CREATE TABLE ORDERS_DETAILS(ID bigint generated BY default as identity NOT NULL,
                    ORDERS_ID bigint NOT NULL COMMENT '订单ID',
                    BOOKS_ID bigint NOT NULL COMMENT '图书ID',
                    CREATE_TIME DATETIME COMMENT'创建时间',
                    ORDER_COUNT INT NOT NULL COMMENT '下单数量',
                    TOTAL_PRICE INT NOT NULL COMMENT '总金额',
                    ORDER_DETAILS_STATUE VARCHAR(2) NOT NULL COMMENT'订单状态'
);

DROP TABLE IF EXISTS POINTS;
CREATE TABLE POINTS(ID bigint generated BY default as identity NOT NULL,
                    ORDERS_ID bigint NOT NULL COMMENT '订单ID',
                    CREATE_TIME DATETIME COMMENT'创建时间',
                    POINTS INT NOT NULL COMMENT'积分值',
                    STATUE  VARCHAR(2) NOT NULL COMMENT '状态'
);

